version: '3'
services:
  rpdr-prono-frontend:
    build: ./src/client
    env_file: .env
    ports:
      - 3000:3000
  rpdr-prono-backend:
    build: ./src/server
    env_file: .env
    ports:
      - 3002:3002